"""
Checks whether the LALM audio_tower encoders accept variable-length (unpadded)
input instead of the fixed window they're currently padded to regardless of
clip length (T_audio=750 either way -- see foundation_encoder_summary.txt for
why that matters for file size).

Generated by Claude Code.

Usage:
    python interpretability/check_variable_length_encoding.py --encoder qwen2-audio --n 20
    python interpretability/check_variable_length_encoding.py --encoder audio-flamingo-3 --n 20
"""
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import argparse
import random

import audiofile
import numpy as np
import torch
import torch.nn.functional as F
from transformers import AutoProcessor

from models.audio_encoder.preprocessing_aibo import (
    LALM_MODELS,
    SAMPLING_RATE,
    _load_aibo_index,
    _load_lalm_full_model,
)


def encode(model, feature_extractor, signal, device, do_pad, encoder_name):
    # Leave `padding` unspecified for the padded case -- that's what the real
    # preprocessing scripts do. Explicit padding="max_length" is NOT the same
    # thing: it falls back to the feature extractor's generic 30s/3000-frame
    # default, longer than this checkpoint's max_source_positions=1500, and
    # crashes for an unrelated reason. do_not_pad is the actual test case.
    kwargs = dict(sampling_rate=SAMPLING_RATE, return_tensors="pt", return_attention_mask=True)
    if not do_pad:
        kwargs["padding"] = "do_not_pad"
    inputs = feature_extractor(signal, **kwargs)
    input_features = inputs.input_features.to(device=device, dtype=model.dtype)

    # SDPA wants attn_mask as bool or matching the query dtype; the feature
    # extractor returns plain int, which errors once it reaches attention.
    mask = inputs.attention_mask.to(device=device, dtype=torch.bool)

    with torch.no_grad():
        # Qwen2AudioEncoder takes `attention_mask` (and ignores it); Audio
        # Flamingo 3's encoder requires a mask and takes `input_features_mask`.
        if encoder_name == "audio-flamingo-3":
            out = model(input_features, input_features_mask=mask)
        else:
            out = model(input_features, attention_mask=mask)
    return out.last_hidden_state.squeeze(0).float().cpu()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--encoder", default="qwen2-audio", choices=list(LALM_MODELS))
    parser.add_argument("--n", type=int, default=20, help="Number of AIBO clips to test.")
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model_id = LALM_MODELS[args.encoder]

    print(f"Loading {model_id}...")
    processor = AutoProcessor.from_pretrained(model_id)
    feature_extractor = processor.feature_extractor
    full_model = _load_lalm_full_model(args.encoder, model_id)
    backbone = full_model.model if hasattr(full_model, "model") else full_model
    model = backbone.audio_tower
    del backbone.language_model
    if args.encoder == "audio-flamingo-3":
        model = model.float()  # its LayerNorm errors on fp16 input, see preprocessing_aibo.py
    model = model.to(device).eval()

    index = _load_aibo_index()
    random.seed(args.seed)
    sample = random.sample(index, args.n)

    print(f"\n{'duration':>9}  {'T_pad':>6}  {'T_nopad':>8}  {'cos_sim':>8}")
    sims, frames_per_sec = [], []
    errors = 0

    for file_path, _ in sample:
        signal, _ = audiofile.read(file_path, always_2d=False)
        duration = len(signal) / SAMPLING_RATE

        try:
            padded = encode(model, feature_extractor, signal, device, True, args.encoder)
            unpadded = encode(model, feature_extractor, signal, device, False, args.encoder)
        except Exception as e:
            print(f"{duration:8.2f}s   ERROR: {e}")
            errors += 1
            continue

        if torch.isnan(unpadded).any() or torch.isinf(unpadded).any():
            print(f"{duration:8.2f}s  {padded.shape[0]:6d}  {unpadded.shape[0]:8d}   NaN/Inf in unpadded output!")
            errors += 1
            continue

        # Compare mean-pooled vectors: expect some drop from 1.0 (padding
        # dilutes the mean), but a large/inconsistent drop would mean the
        # unpadded pass isn't just "the same content, less diluted".
        pooled_padded = padded.mean(dim=0)
        pooled_unpadded = unpadded.mean(dim=0)
        cos = F.cosine_similarity(pooled_padded.unsqueeze(0), pooled_unpadded.unsqueeze(0)).item()

        sims.append(cos)
        frames_per_sec.append(unpadded.shape[0] / duration)
        print(f"{duration:8.2f}s  {padded.shape[0]:6d}  {unpadded.shape[0]:8d}  {cos:8.3f}")

    print(f"\n{errors}/{len(sample)} samples errored or produced NaN/Inf.")
    if sims:
        # A flat/constant frames-per-second ratio across very different
        # durations is the key signal: it means T_audio genuinely scales
        # with content instead of being silently capped somewhere else.
        print(f"Mean cosine similarity (padded vs. unpadded pooled): {np.mean(sims):.3f} (std {np.std(sims):.3f})")
        print(f"T_audio(unpadded) / true_duration: mean {np.mean(frames_per_sec):.2f} frames/sec, std {np.std(frames_per_sec):.2f}")


if __name__ == "__main__":
    main()
